vim.opt.autoindent  = true
vim.opt.signcolumn  = 'yes'
vim.opt.cursorline  = false
vim.opt.pumheight   = 10
vim.opt.clipboard   = { "unnamed", "unnamedplus" }
vim.opt.cmdheight   = 1
vim.opt.completeopt = 'menuone,noselect'
vim.opt.expandtab   = true
vim.opt.hidden      = true
vim.opt.ignorecase  = true
vim.opt.mouse       = 'a'
vim.opt.ruler       = false
vim.opt.showcmd     = false
vim.opt.showmode    = false
vim.opt.swapfile    = false
vim.opt.wrap        = false
vim.opt.number      = true
vim.opt.shiftwidth  = 4
vim.opt.signcolumn  = 'yes'
vim.opt.softtabstop = 4
vim.opt.splitright  = true
vim.opt.tabstop     = 4
vim.wo.numberwidth  = 2
vim.cmd 'let g:python3_host_prog = "/opt/homebrew/bin/python3"'
