vim.cmd 'source ~/.config/nvim/vim/mappings.vim'
vim.cmd 'source ~/.config/nvim/vim/functions.vim'
vim.cmd 'source ~/.config/nvim/vim/commands.vim'
-- vim.cmd 'source ~/.config/nvim/vim/onedark.vim'
require 'settings.options'
require 'plugins'
